### ISSUE TITLE
Deploy DAMS Manager 2.54

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/damsmanager#134]
Version: 2.54
Release Manager: @lsitu 
Product Owner: @gamontoya 
Operations: @rstanonik 

Review Checklist:
- [x] [Adjust code for RDCP download statistics](https://github.com/ucsdlib/damsmanager/issues/128)
- [x] [Adjust DAMS statistics to include hits/downloads per collection from SC&A exhibits](https://github.com/ucsdlib/damsmanager/issues/127)
- [x] [Excel ingest - make column header validation case insensitive](https://github.com/ucsdlib/damsmanager/issues/130)
- [x] [Ingest created duplicate objects in the DAMS - CCDB](https://github.com/ucsdlib/damspas/issues/264)

**Comment by lsitu** [comment]
@gamontoya I've created release 2.54 for damsmanager and deployed it to staging. It's ready on staging for review now. Thanks.
The following changes are included in this release:

- [Adjust code for RDCP download statistics](https://github.com/ucsdlib/damsmanager/issues/128)
- [Adjust DAMS statistics to include hits/downloads per collection from SC&A exhibits](https://github.com/ucsdlib/damsmanager/issues/127)
- [Excel ingest - make column header validation case insensitive](https://github.com/ucsdlib/damsmanager/issues/130)
- [Ingest created duplicate objects in the DAMS - CCDB](https://github.com/ucsdlib/damspas/issues/264)

**Comment by mcritchlow** [comment]
@lsitu thanks for making that list, I like the idea of having that as part of the deploy ticket template.

I added it as a checklist to the description, then we can ensure the review checklist is complete for tickets before they're approved. What do you think?

**Comment by lsitu** [comment]
@mcritchlow It looks nice! Thanks.

**Comment by gamontoya** [comment]
@lsitu Approved for prod.

**Comment by lsitu** [comment]
Thank you all for verifying the deployment.
@rstanonik I've merged the release branch to the master branch and it's ready for prod now. Thanks.

**Comment by stanonik** [comment]
Damsmanager was deployed to production this morning

**Comment by mcritchlow** [comment]
Thanks @rstanonik!
