### ISSUE TITLE
Release 2.61

### ISSUE THREAD

**Issue by lsitu** [ucsdlib/damsmanager#193]
### Descriptive summary

Version: 2.61
Release Manager: @lsitu
Product Owner and Reviewers: @gamontoya
Operations: @jhriv or @rstanonik 

To Verify/Review:
* [x] #183 (Change authority label matching in import tools: spaces and punctuation)
* [x] #186  (Fix database error for Oct 16 statistics)
* [ ] https://github.com/ucsdlib/damspas/issues/360 (Update attribution note for all objects referencing DLDP)

**Comment by lsitu** [comment]
@gamontoya The new release is ready on staging for review now. I think we may need @GregReser to test and verify the functionality of authority label matching on https://github.com/ucsdlib/damsmanager/issues/183. Thanks.

**Comment by gamontoya** [comment]
@lsitu Greg is out this week. Can this wait?

**Comment by gamontoya** [comment]
@GregReser Can you please confirm authority label matching on staging?

**Comment by mcritchlow** [comment]
Wondering if someone else from @ucsdlib/domm could verify in @GregReser's absence?

Not that we're in a rush. Just curious.

**Comment by lsitu** [comment]
@gamontoya I think next Tuesday when Greg is back will be fine since this is not an urgent fix.

**Comment by arwenhutt** [comment]
I doubt I'd be able to get to this before Greg gets back :( I'm buried under a mountain already.  @remerjohnson do you have the bandwidth to test this?

**Comment by remerjohnson** [comment]
@arwenhutt Yeah I could test out #183 on staging

**Comment by remerjohnson** [comment]
So, I ran a test subject ingest with the term variations Greg had in his ticket, plus some ones I made up for good measure, and they all got matched to the original value/ARK. I'd say it's confirmed. @mcritchlow @gamontoya

**Comment by gamontoya** [comment]
Thank you for testing! @remerjohnson

**Comment by gamontoya** [comment]
@lsitu Is #186 confirmed fixed?

**Comment by lsitu** [comment]
@gamontoya Yes. I think so. But we need to run it on prod.

**Comment by gamontoya** [comment]
@lsitu This can be pushed to prod whenever it's convenient.

**Comment by lsitu** [comment]
@gamontoya Sure. I've merged it into the master branch.
@rstanonik @jhriv DAMS Manager release 2.61 is ready for prod now. Thanks.

**Comment by lsitu** [comment]
@rstanonik Have you got a chance to deploy damsmanager release 2.61 to prod? Thanks.

**Comment by rstanonik** [comment]
Sorry, I overlooked the request.
I deployed it this morning.

**Comment by lsitu** [comment]
Thanks @rstanonik.

**Comment by lsitu** [comment]
@gamontoya I just ran dams statistics on prod to generate the stats for Oct. 16 that was failed earlier and it works. I am closing the deployment ticket now. Thanks @rstanonik for deploying it to prod.
