### ISSUE TITLE
Release 2.64

### ISSUE THREAD

**Issue by lsitu** [ucsdlib/damsmanager#233]
### Descriptive summary
Version: 2.64
Release Manager: @lsitu
Product Owner and Reviewers: @gamontoya
Operations: @jhriv or @rstanonik 

To Verify/Review:
- [ ] #219 RDCP object views do not get logged uniquely
- [ ] #225 RDCP object views from external points of entry do not get logged at all 
- [ ] #227 RDCP object views get logged inconsistently from session to session
- [x] #162 MARC to CSV Mapping: add 79X, 245 $c
- [x] #217 Added support to validate Begin/End date for Excel Import

**Comment by lsitu** [comment]
@rstanonik / @jgorney We need to update the tables stats_dlp_object_access and stats_file_download in PostgreSQL with the scripts in [stats-update_ip.sql]( https://github.com/ucsdlib/damsmanager/blob/develop/conf/stats-update_ip.sql) as part of this deployment. I've updated it on QA for my tests. Could you run the scripts for the staging environment when you are convenient? And we need to update it on prod once we are ready to deploy it there as well.

Also, could we append the following lines to damsmanager.properties on QA, staging, and prod? 
https://github.com/ucsdlib/damsmanager/blob/develop/conf/damsmanager.properties#L37-L40.

Both changes are required for the new features contains in this release for dams statistics and we may need to restart tomcat once the changes are done.  Thanks.

**Comment by rstanonik** [comment]
I updated damsmanager.properties in QA and restarted the lib-ingest-qa tomcat.

Does the order of changes matter?
That is, must the tables be updated before damsmanager.properties?

**Comment by rstanonik** [comment]
I made the changes to damsmanager.properties in Staging and Production and restarted the ingest tomcats.

**Comment by gamontoya** [comment]
@lsitu Did you get Ho Jung and Greg to review the related tickets listed above?

**Comment by lsitu** [comment]
@gamontoya I haven't add them to the review list yet. But I think we can add them in once we get the new release for damsmanger setup on staging.

**Comment by jgorney** [comment]
Hi @lsitu I've made the database changes in staging as requested.

**Comment by lsitu** [comment]
Thanks @jgorney. It looks good.

**Comment by lsitu** [comment]
@rstanonik I got a null error for the configuration params added. It looks like both params (dams.stats.se.patterns and dams.stats.se.data) are missing from /pub/data2/damsmanager/damsmanager.properties on lib-hydratail-staging. Could you double check? Thanks.

**Comment by rstanonik** [comment]
I changed the config on lib-ingest-staging.  I forgot that you are running damsmanager on lib-hydratail-staging.  I changed the config on lib-hydratail-staging and restarted the tomcat. 

Do you still need lib-ingest-staging?  Can I turn it off?

**Comment by lsitu** [comment]
@rstanonik Have we made the same changes for damsmanager on prod and QA? I think @jhriv had changed it for a while with damsmanager on staging already. I don't think we may still need lib-ingest-staging. And yes, I believe we can turn it off in this case.

**Comment by rstanonik** [comment]
Yes, the changes were made to prod and QA, which have damsmanager running on their ingest servers.

**Comment by lsitu** [comment]
@rstanonik Thanks. Do we have any plans to move damsmanager on prod and QA to lib-hydrahead like what @jhriv hand done for staging in the past?

**Comment by lsitu** [comment]
@hjsyoo Do you have a test doi link that I can use to test the RDCP Objects Views on staging? I think a test doi link should be something like https://doi.org/10.5072/FK2xxxxxx. Thanks.

**Comment by hjsyoo** [comment]
@lsitu Sure, any of these should work for testing:
https://doi.org/10.6075/J02B8W60
https://doi.org/10.6075/J0W66HP1
https://doi.org/10.6075/J0H12ZXW
Are you testing external links, or just entering these into the address bar? If you want to test a view that hasn't been getting logged and is coming from an external link, try this:
https://pdfs.semanticscholar.org/6664/17af86193e143a85b4ecbed2124bc893944c.pdf
On the left column of the first page, under Data Availability Statement, click on the DOI link for 10.6075/J02Z13F5.

**Comment by lsitu** [comment]
@hjsyoo I was thinking about testing the basic functionalities by entering those external link into the address bar. However, I can follow the steps you provided to test it in pdf though. But it looks like all the links you provide are all formal DOI links and I can't test it on prod until we deploy damsmanager there. Do you have a staging DOI link that I can test it on staging environment (librarytest.ucsd.edu)?

**Comment by hjsyoo** [comment]
@lsitu I don't have a DOI that points to librarytest at the moment, but can easily create one. I'll let you know when it's active.

**Comment by hjsyoo** [comment]
I just minted https://doi.org/10.5072/FK2XW4H173 for this page: https://librarytest.ucsd.edu/dc/object/bb2391869d, but I did it by visiting the page first, so keep in mind that one curator view is already logged for today. You might want to wait until tomorrow to do the test?

**Comment by lsitu** [comment]
@hjsyoo Thanks. I'll do more tests tomorrow then.

**Comment by rstanonik** [comment]
I'm ready to move damsmanager from ingest to hydratail in QA.  Any discussion or scheduling necessary?

**Comment by rstanonik** [comment]
I'm ready to move damsmanager from ingest to hydratail in QA.  Any discussion or scheduling required before I do that?

**Comment by lsitu** [comment]
@rstanonik For the changes on QA, I think anytime should be fine. Thanks.

**Comment by lsitu** [comment]
@rstanonik Thanks. I just tried to access https://libraryqa.ucsd.edu/damsmanager/controlPanel.do but got 403 error:
HTTP Status 403 - Access to the requested resource has been denied.

**Comment by rstanonik** [comment]
Yes, me too.  I'm trying to understand why.  Any ideas?

**Comment by lsitu** [comment]
@rstanonik I don't see anything in the tomcat log related to damsmanager. It could be related to the AD roles. Is tomcat on lib-hydratail-qa able to access AD server?

**Comment by rstanonik** [comment]
Yes, it is connected to AD.

**Comment by lsitu** [comment]
@rstanonik Hmm, it's weird and I don't see any related info in the tomcat log.

**Comment by rstanonik** [comment]
The server.xml differ between ingest and hydratail.  I think hydratail is missing some authentication config, which I'll copy from ingest tomorrow.

**Comment by lsitu** [comment]
@rstanonik Thanks. Yep, that could be an issue.

**Comment by rstanonik** [comment]
Does damsmanager authentication depend upon access to a postgresql database?

**Comment by lsitu** [comment]
No. It depends upon AD.

**Comment by rstanonik** [comment]
If QA damsmanager looks okay, then we can pick a time to move damsmanager from ingest to hydratail in production.

**Comment by rstanonik** [comment]
I have a jenkins plan to deploy damsmanager.

It deploys to Staging automatically, from the release branch.  Is that correct?

It deploys to QA from the release branch too.  Is that correct?  And should that be automatic too?

**Comment by lsitu** [comment]
@rstanonik For staging, yes, it's correct. For QA, since we are going to use it for subject conversion next, I think we can set it up to deploy it from the master branch for now and disable the automatic deployment. Thanks.

**Comment by gamontoya** [comment]
@lsitu Can we close this ticket?

**Comment by lsitu** [comment]
@gamontoya No. We haven't deployed it yet. I am still testing the external links views with the DOI link that @hjsyoo created, which could be verified tomorrow morning. But I think we can have @hjsyoo and @GregReser to review those features above at the mean time. What do you think?

**Comment by lsitu** [comment]
@rstanonik QA damsmanager looks good, and I think we can pick a time to move damsmanager from ingest to hydratail in production. But I would suggest to move ticket [Update Tomcat configuration for database connection pooling](https://github.com/ucsdlib/damsrepo/issues/62) to prod at the same time since damsmanager and damrepo will share the same database connection pool. 
@mcritchlow What time do you suggest to move it forward?

**Comment by lsitu** [comment]
@gamontoya Sure. I'll post them for reviewing once I verify the result tomorrow morning.

**Comment by lsitu** [comment]
@gamontoya / @hjsyoo / @GregReser I think damsmanager release 2.64 is ready on staging (https://librarytest.ucsd.edu/damsmanager/) for review now. We will deploy it to prod once it's approved. Thanks.

**Comment by GregReser** [comment]
@lsitu #162 MARC to CSV Mapping: add 79X, 245 $c is working correctly

**Comment by GregReser** [comment]
@lsitu #217 Added support to validate Begin/End date for Excel Import

Validation for the number of days in a month is working, but now the format requires a full date (YYYY-MM-DD).  I got this error:  "2018" is too short.

Currently, DAMS Manager allows YYYY or YYYY-MM, or YYYY-MM-DD.  We want to continue to allow this.

**Comment by lsitu** [comment]
@GregReser Sure. I'll add date validation support for YYYY format and YYYY-MM format. Thanks.

**Comment by hjsyoo** [comment]
@lsitu I initiated testing for unique views and external link entry today, and cleared the cache between each round of test. I'll download the stats report tomorrow, but will be at an all day event and may not be able to report on results until Tuesday of next week. Is that timing okay for you?

**Comment by lsitu** [comment]
@mcritchlow I've added PR #234 above to support the validation of date time formats YYYY and YYYY-MM. It's ready for review now. Thanks.

**Comment by hjsyoo** [comment]
@lsitu Just wanted to make sure - I need to test RDCP views in librarytest.ucsd.edu/dc, right?

**Comment by lsitu** [comment]
@hjsyoo Yes, if you are convenient to test the unit views for the basic support. And I think we can move it to prod so that you can test it more with the external links for accuracy. Just let us know if you think the basic support for the unique views looks good and we can move it forward to prod for more tests. Thanks.

**Comment by hjsyoo** [comment]
@lsitu Here are results from testing google sheet clicks on librarytest.ucsd.edu/dc.

Behavior: After adding the URLs to my google sheet, I clicked on an object URL, scrolled down to tbe bottom of the page, then closed the tab. I then returned to my google sheet and clicked on the next object URL.  I cleared my cache between the two rounds of clicks, but not between the object clicks. 

  |   | Expected views | Observed views
-- | -- | -- | --
Obj/Comp title | ARK | Non-curator | Curator | Non-curator | Curator
  |   |   |   |   |  
Mapping sound production by Gulf Corvina at a spawning aggregation site | https://librarytest.ucsd.edu/dc/object/bb4438832x | 2+ | NA | 3 | 0
Data from: A Living Vector Field Reveals Constraints on Galactose Network Induction in Yeast | https://librarytest.ucsd.edu/dc/object/bb7920789g | 2+ | NA | 3 | 0
Training Bees to a Feeder | https://librarytest.ucsd.edu/dc/object/bb8977691g | 2+ | NA | 3 | 0
Area W, Southern Building Complex | https://librarytest.ucsd.edu/dc/object/bb4540769z | 2+ | NA | 3 | 0
Map of Scripps CO2 Program Sampling Stations | https://librarytest.ucsd.edu/dc/object/bb32791536 | 2+ | NA | 3 | 0
San Diego County Bee Species List | https://librarytest.ucsd.edu/dc/object/bb8534049c | 2+ | NA | 3 | 0
  |   |   |   |   |  
  |   |   |   |   |  
Women's Healthy Eating and Living (WHEL) Study | https://librarytest.ucsd.edu/dc/object/bb2493244b | NA | 2+ | 3 | 0
Aerosol and Cloud Observations in La Jolla, CA, in May-June 2011 during SOLEDAD (Stratocumulus Observations of Los-Angeles Emissions Derived Aerosol-Droplets) | https://librarytest.ucsd.edu/dc/object/bb2391869d | NA | 2+ | 3 | 0
Africanized Honeybees | https://librarytest.ucsd.edu/dc/object/bb12301807 | NA | 2+ | 3 | 0
SOCCOM float data - Snapshot 2016-11-28 | https://librarytest.ucsd.edu/dc/object/bb2801340v | NA | 2+ | 3 | 0
AVON02MV-009D (dredge, rock) | https://librarytest.ucsd.edu/dc/object/bb2527042r | NA | 2+ | 3 | 0

So, it looks like the views were indeed logged, but there was an extra visit logged for every object (3 observed, but only 2 actual visits). Also, I'm not sure if this properly tested unique views. If a user clears their cache between visits, should this be seen as a new unique view? I was on wireless on campus, but I did not log out during the testing.

**Comment by lsitu** [comment]
@hjsyoo Thank you very much for your tests. While reviewing the data on the weblog, I see there were two object views from IP 137.110.89.134 for each object that you used for test and there was one object view from IP 137.110.93.147. So I think your tests are good and the Observe views (3) above is the pages views. If you click on the `Unique Views` link/button on the top right corner of the the report page, or use the following link [RDCP Objects Views by Month (Unique Views)](https://librarytest.ucsd.edu/damsmanager/statsRdcpUsage.do?unique), you will get the report for Unique Views. Sorry about the confusion. Please let me know if you have any questions. Thanks.

**Comment by lsitu** [comment]
@GregReser I've added the support to validate date time format YYYY and YYYY-MM and deployed it to staging. The feature is ready on [staging](https://librarytest.ucsd.edu/damsmanager/) for your review now. Thanks.

**Comment by hjsyoo** [comment]
@lsitu Thanks for pointing out the unique views page. They seem to indicate 2 views per object. So, if I understand correctly, clearing the cache causes the next visit to be logged as a unique view? I think this is logical way to parse visits, as most users (with multiple visits in a session) won't likely be clearing the cache during the session.

I still don't understand why an extra visit was logged for each object, though, in total views. Since I didn't log out of my computer or my wireless connection, I assume that my IP during both rounds of clicks was 137.110.89.134? Why do you think there was an object view from IP 137.110.93.147? Was that address linked to me as well?

**Comment by hjsyoo** [comment]
@lsitu Also, I'm curious what are the ARKs that start with "bd..."? They are included on the stats reports for staging, with no title information associated with those line items.

**Comment by lsitu** [comment]
@hjsyoo I don't think clearing the cache will cause the next visit to be logged as a unique view. We still got two views from the same IP 137.110.89.134 though you clear the cache for each round of test may explain it. But if your wireless session is timeout during your tests, then I think you will be assigned another IP.
Here are the object views logged in the Apache weblog for the first object https://librarytest.ucsd.edu/dc/object/bb4438832x:
```
Jun 22 11:06:01 librarytest apache[23239]: librarytest.ucsd.edu 137.110.89.134 - - [22/Jun/2018:11:06:00 -0700] "GET /dc/object/bb4438832x HTTP/1.1" 200 25489 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 11:12:42 librarytest apache[23239]: librarytest.ucsd.edu 137.110.89.134 - - [22/Jun/2018:11:12:41 -0700] "GET /dc/object/bb4438832x HTTP/1.1" 200 25489 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 12:57:02 librarytest apache[23239]: librarytest.ucsd.edu 137.110.93.147 - - [22/Jun/2018:12:57:02 -0700] "GET /dc/object/bb4438832x HTTP/1.1" 200 25489 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
```

I don't know how the tests were performed but the apache weblog showing that the object got  hits three times within two hours. In this case, the wireless session may expire so another IP could be assigned.

**Comment by hjsyoo** [comment]
@lsitu Thanks. The timing is odd on that log, as it suggests I reopened that object after the lunch break. I'm certain I did both rounds of testing before lunch, which would explain the first two hits. Can you give me a copy of the weblog for all hits on librarytest for Jun 22 between 11 am and 2 pm? Or can you tell if all of the third hits were after 12:45 that day? I'm curious if all 11 objects were visited twice before lunch (11:30-12:45 that day) and once after lunch?

**Comment by GregReser** [comment]
@lsitu date time format validation is working correctly.

**Comment by lsitu** [comment]
@hjsyoo The weblog is big and mixed with tons of other accesses to the libraries, which is hard for you to read. So I just grabbed all those hits that were counted for your tests. And yes, it's showing that all 11 objects were visited twice before lunch (11:30-12:45 that day) and once after lunch started at 12:51pm:
```
Jun 22 11:06:01 librarytest apache[23239]: librarytest.ucsd.edu 137.110.89.134 - - [22/Jun/2018:11:06:00 -0700] "GET /dc/object/bb4438832x HTTP/1.1" 200 25489 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 11:06:31 librarytest apache[23239]: librarytest.ucsd.edu 137.110.89.134 - - [22/Jun/2018:11:06:30 -0700] "GET /dc/object/bb7920789g HTTP/1.1" 200 94652 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 11:06:56 librarytest apache[23239]: librarytest.ucsd.edu 137.110.89.134 - - [22/Jun/2018:11:06:55 -0700] "GET /dc/object/bb8977691g HTTP/1.1" 200 20961 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 11:09:18 librarytest apache[23239]: librarytest.ucsd.edu 137.110.89.134 - - [22/Jun/2018:11:09:12 -0700] "GET /dc/object/bb4540769z HTTP/1.1" 200 769277 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 11:09:35 librarytest apache[23239]: librarytest.ucsd.edu 137.110.89.134 - - [22/Jun/2018:11:09:34 -0700] "GET /dc/object/bb32791536 HTTP/1.1" 200 21415 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 11:09:44 librarytest apache[23239]: librarytest.ucsd.edu 137.110.89.134 - - [22/Jun/2018:11:09:44 -0700] "GET /dc/object/bb8534049c HTTP/1.1" 200 25244 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 11:12:19 librarytest apache[23239]: librarytest.ucsd.edu 137.110.89.134 - - [22/Jun/2018:11:12:18 -0700] "GET /dc/object/bb7920789g HTTP/1.1" 200 94652 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 11:12:42 librarytest apache[23239]: librarytest.ucsd.edu 137.110.89.134 - - [22/Jun/2018:11:12:41 -0700] "GET /dc/object/bb4438832x HTTP/1.1" 200 25489 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 11:13:00 librarytest apache[23239]: librarytest.ucsd.edu 137.110.89.134 - - [22/Jun/2018:11:13:00 -0700] "GET /dc/object/bb8977691g HTTP/1.1" 200 20961 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 11:13:20 librarytest apache[23239]: librarytest.ucsd.edu 137.110.89.134 - - [22/Jun/2018:11:13:15 -0700] "GET /dc/object/bb4540769z HTTP/1.1" 200 769277 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 11:13:34 librarytest apache[23239]: librarytest.ucsd.edu 137.110.89.134 - - [22/Jun/2018:11:13:33 -0700] "GET /dc/object/bb32791536 HTTP/1.1" 200 21415 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 11:13:54 librarytest apache[23239]: librarytest.ucsd.edu 137.110.89.134 - - [22/Jun/2018:11:13:54 -0700] "GET /dc/object/bb8534049c HTTP/1.1" 200 25244 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 11:25:07 librarytest apache[23239]: librarytest.ucsd.edu 137.110.89.134 - - [22/Jun/2018:11:25:06 -0700] "GET /dc/object/bb2493244b HTTP/1.1" 200 108381 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 11:25:20 librarytest apache[23239]: librarytest.ucsd.edu 137.110.89.134 - - [22/Jun/2018:11:25:19 -0700] "GET /dc/object/bb2391869d HTTP/1.1" 200 112861 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 11:25:38 librarytest apache[23239]: librarytest.ucsd.edu 137.110.89.134 - - [22/Jun/2018:11:25:37 -0700] "GET /dc/object/bb12301807 HTTP/1.1" 200 23312 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 11:25:57 librarytest apache[23239]: librarytest.ucsd.edu 137.110.89.134 - - [22/Jun/2018:11:25:56 -0700] "GET /dc/object/bb2801340v HTTP/1.1" 200 42122 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 11:26:15 librarytest apache[23239]: librarytest.ucsd.edu 137.110.89.134 - - [22/Jun/2018:11:26:14 -0700] "GET /dc/object/bb2527042r HTTP/1.1" 200 27564 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 11:27:25 librarytest apache[23239]: librarytest.ucsd.edu 137.110.89.134 - - [22/Jun/2018:11:27:23 -0700] "GET /dc/object/bb2493244b HTTP/1.1" 200 108381 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 11:27:41 librarytest apache[23239]: librarytest.ucsd.edu 137.110.89.134 - - [22/Jun/2018:11:27:40 -0700] "GET /dc/object/bb2391869d HTTP/1.1" 200 112861 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 11:27:58 librarytest apache[23239]: librarytest.ucsd.edu 137.110.89.134 - - [22/Jun/2018:11:27:57 -0700] "GET /dc/object/bb12301807 HTTP/1.1" 200 23312 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 11:28:19 librarytest apache[23239]: librarytest.ucsd.edu 137.110.89.134 - - [22/Jun/2018:11:28:18 -0700] "GET /dc/object/bb2801340v HTTP/1.1" 200 42122 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 11:28:36 librarytest apache[23239]: librarytest.ucsd.edu 137.110.89.134 - - [22/Jun/2018:11:28:36 -0700] "GET /dc/object/bb2527042r HTTP/1.1" 200 27564 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 12:51:02 librarytest apache[23239]: librarytest.ucsd.edu 137.110.93.147 - - [22/Jun/2018:12:51:02 -0700] "GET /dc/object/bb12301807 HTTP/1.1" 200 21249 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 12:52:03 librarytest apache[23239]: librarytest.ucsd.edu 137.110.93.147 - - [22/Jun/2018:12:52:01 -0700] "GET /dc/object/bb2391869d HTTP/1.1" 200 108016 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 12:53:03 librarytest apache[23239]: librarytest.ucsd.edu 137.110.93.147 - - [22/Jun/2018:12:53:02 -0700] "GET /dc/object/bb2493244b HTTP/1.1" 200 103472 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 12:54:02 librarytest apache[23239]: librarytest.ucsd.edu 137.110.93.147 - - [22/Jun/2018:12:54:02 -0700] "GET /dc/object/bb2527042r HTTP/1.1" 200 25475 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 12:55:02 librarytest apache[23239]: librarytest.ucsd.edu 137.110.93.147 - - [22/Jun/2018:12:55:02 -0700] "GET /dc/object/bb2801340v HTTP/1.1" 200 39752 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 12:56:02 librarytest apache[23239]: librarytest.ucsd.edu 137.110.93.147 - - [22/Jun/2018:12:56:02 -0700] "GET /dc/object/bb32791536 HTTP/1.1" 200 21415 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 12:57:02 librarytest apache[23239]: librarytest.ucsd.edu 137.110.93.147 - - [22/Jun/2018:12:57:02 -0700] "GET /dc/object/bb4438832x HTTP/1.1" 200 25489 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 12:58:06 librarytest apache[23239]: librarytest.ucsd.edu 137.110.93.147 - - [22/Jun/2018:12:58:02 -0700] "GET /dc/object/bb4540769z HTTP/1.1" 200 769277 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 12:59:03 librarytest apache[23239]: librarytest.ucsd.edu 137.110.93.147 - - [22/Jun/2018:12:59:02 -0700] "GET /dc/object/bb7920789g HTTP/1.1" 200 94652 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 13:00:03 librarytest apache[23239]: librarytest.ucsd.edu 137.110.93.147 - - [22/Jun/2018:13:00:02 -0700] "GET /dc/object/bb8534049c HTTP/1.1" 200 25244 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
Jun 22 13:01:02 librarytest apache[23239]: librarytest.ucsd.edu 137.110.93.147 - - [22/Jun/2018:13:01:02 -0700] "GET /dc/object/bb8977691g HTTP/1.1" 200 20961 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
```

**Comment by hjsyoo** [comment]
@lsitu Thank you for the log output! Looking at the timestamps, I'm guessing the post-lunch views were machine generated. Note how almost all of them took place exactly 2 seconds into the minute? My morning views are much more irregular, because they were human generated.

**Comment by hjsyoo** [comment]
@lsitu By the way, I would be fine with deploying to prod, given that at least the views registered in the log. This is a definite improvement, and we can do another set of tests in July.

**Comment by lsitu** [comment]
@hjsyoo Thanks.

**Comment by lsitu** [comment]
@gamontoya Are we ready to move damsmanager release 2.64 to prod now?

**Comment by gamontoya** [comment]
@GregReser @hjsyoo Thank you for following up and testing.

@lsitu This is now ready for prod.

**Comment by lsitu** [comment]
Thanks @gamontoya.
@rstanonik I'd merged the changes for damsmanager release 2.64 to the master branch yesterday when we worked together to set up the  Jenkins plan with tag deployment on staging. So we are ready to move it to prod now. Thanks.

**Comment by rstanonik** [comment]
It will deploy to production tomorrow morning.

**Comment by rstanonik** [comment]
It deployed this morning

**Comment by lsitu** [comment]
@rstanonik / @jgorney Thanks. Could we update the tables for dams statistics and check that damsmanager.properties is updated for the required configuration on prod? See comment https://github.com/ucsdlib/damsmanager/issues/233#issuecomment-397743008.
