### ISSUE TITLE
DAMS Manager Release 2.66

### ISSUE THREAD

**Issue by lsitu** [ucsdlib/damsmanager#245]
### Descriptive summary
Version: 2.66
Release Manager: @lsitu
Product Owner and Reviewers: @gamontoya
Operations: @jhriv or @rstanonik 

To Verify/Review:
- [ ] #241 METS/MODS to CSV not importing subjects
- [ ] #243 Update `Restricted - cultural sensitivity` access override
- [ ] #246 Update `Restricted - cultural sensitivity` access override to allow for license restriction

**Comment by lsitu** [comment]
@gamontoya @GregReser We've deployed damsmanager release 2.66 to both QA and staging. It's ready for review now. Thanks.

**Comment by gamontoya** [comment]
@lsitu Should we hold off until you've implemented #246 ?

**Comment by lsitu** [comment]
@gamontoya Sure.

**Comment by lsitu** [comment]
@gamontoya /@GregReser I've deployed the latest code changes for ticket https://github.com/ucsdlib/damsmanager/issues/246 to staging and QA, along with this deployment is the recent changes for damsrepo on master branch. I think you can start your review to test it on QA and staging now.

**Comment by lsitu** [comment]
@gamontoya Are we ready to push damsmanager release 2.66 to prod along with damspas release 1.82 now? I think those notes change above could affect the matadata-only display behavior with new ingest.

**Comment by gamontoya** [comment]
@lsitu Yes. This can be pushed to prod.

**Comment by lsitu** [comment]
@gamontoya Thanks.
@rstanonik The codes are in master branch and we are ready to move it to prod now. Thanks.

**Comment by gamontoya** [comment]
@lsitu Was this deployed?

**Comment by lsitu** [comment]
@gamontoya Yes. I think @rstanonik had deployed it this Monday morning.

**Comment by gamontoya** [comment]
@lsitu Thank you.

**Comment by lsitu** [comment]
@rstanonik Did this release deployed on prod again after you deployed it last Monday? We found it carried the changes that we committed on Tuesday Sep 11 (https://github.com/ucsdlib/damsmanager/commit/9dfcb5abcd564f8cd3bf078dcc89ef7d15a08f52), which hasn't been tested yet. @remerjohnson ran into an issue with our latest deployment, which is related to the big commit on Tuesday, Sep 11 and we may need to fully test it before we can release it to prod.
Is it possible to revert it to the version that you deployed on Monday, Sep 10? Thanks.

**Comment by rstanonik** [comment]
Sorry, it did deploy on Sept 12 because I forgot to remove a deploy trigger.  I'll rollback to the version from Sept 10.  I'll let you know when that's done

**Comment by rstanonik** [comment]
I restored damsmanager.war from Sept 10 and restarted the tomcat.
Can you confirm I got the right version?

**Comment by lsitu** [comment]
@rstanonik I just tested it and I think it's the correct version. Thanks. @remerjohnson The latest damsmanager on prod should has no control character fix now. We'll do a fully test on staging and deploy it again later. Sorry about it.

**Comment by remerjohnson** [comment]
@lsitu @rstanonik That's all right. It wasn't hard to edit the affected objects, and maybe we found some good things to test the character fix feature. Thanks!
