### ISSUE TITLE
Release 2.67

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damsmanager#260]
### Descriptive summary

Version: 2.67
Release Manager: @lsitu
Product Owner and Reviewers: @gamontoya
Operations: @jhriv or @rstanonik

---

### To Verify/Review

- [x] Ignoring escape characters #251 
- [x] Adding multiple header values for identifer #258 
- [x] Adding banner to DAMS Manager staging #254

**Comment by gamontoya** [comment]
@lsitu This is approved for deploying to prod on Tuesday morning.

**Comment by rstanonik** [comment]
damsmanager deployed to production this morning at 6:00am and the tomcat was restarted
