### ISSUE TITLE
Release 2.70

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damsmanager#285]
### Descriptive summary

Version: 2.70
Release Manager: @lsitu
Product Owner and Reviewers: @gamontoya
Operations: @jhriv or @rstanonikbug.

-----
### To Verify

- [x] #262 R&D: Collection Reporting tool 
- [ ] #266 - Address indexing queue wait time
- [ ] #281 - RDCP download counts are inaccurately reported

@lsitu Any more to verify?

**Comment by lsitu** [comment]
@gamontoya DAMS Manager release 2.70 is ready on staging for review now. The URL for the collection report tool is https://librarytest.ucsd.edu/damsmanager/collectionStatusReport.do, or you can access from the first item `Collection Report` on the `DAMS` main menu. Thanks.

**Comment by lsitu** [comment]
Thanks @gamontoya .
@rstanonik The codes for DAMS Manager release 2.70 is ready on master branch and it's for prod now. Thanks.

**Comment by rstanonik** [comment]
DAMS Manager was deployed to production this morning, including a tomcat restart

**Comment by lsitu** [comment]
It looks good. Thanks @rstanonik.

**Comment by gamontoya** [comment]
Kamino cloned this issue to [ucsdlib/damsmanager](https://github.com/ucsdlib/damsmanager/issues/286)

**Comment by gamontoya** [comment]
Kamino cloned this issue to [ucsdlib/damsmanager](https://github.com/ucsdlib/damsmanager/issues/314)
