### ISSUE TITLE
template for binder/epic tickets

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/damsmanager#308]
## Brief description
[brief description]

- [ ] Products proposal: [_link to proposal ticket?_]
- [ ] Initial scope discussion: [ link to ticket if there is one] _this seems to be something we often do which is helpful, but which makes the initial ticket very long and potentially confusing_

### [function] _I think this might be optional & repeatable depending on the project, for different components of the functionality like the batch edit which has two separate pieces export + overlay_
- [ ] spec written, reviewed , and finalized.  [link to ticket]
- [ ] code written.  [link to ticket]
- [ ] testing and updating on QA server.  [link to ticket] _or should this be part of the code item above, perhaps using "review requested" to DOMM (or whomever) prior to a MR?_
- [ ] deployed and tested on production server.  [link to ticket]

_?  anything else ?_
