### ISSUE TITLE
Batch edit functionality (epic)

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/damsmanager#309]
## Brief description
Batch edit functionality for DOMM

- [x] Products proposal and initial scope discussion: https://github.com/ucsdlib/damsmanager/issues/263 
_I think this was the ticket products discussed_

### Batch metadata export 
- [x] spec written, reviewed , and finalized:  https://github.com/ucsdlib/damsmanager/issues/263
- [x] code written:  https://github.com/ucsdlib/damsmanager/issues/301
- [x] testing, changes QA server:  PR https://github.com/ucsdlib/damsmanager/issues/302
- [x] deployed and tested on production server: tbd

### Batch metadata overlay
- [x] spec written, reviewed, and finalized:  https://github.com/ucsdlib/damsmanager/issues/310
- [x] code written:  #321 #322 #323 #324
- [x] testing and updating on staging server:  #345
- [x] deployed and tested on production server:  tbd

**Comment by arwenhutt** [comment]
This ticket is for tracking and coordination across the individual tasks/tickets which are part of this larger functionality.  Discussion and work on the more specific deliverables is still in the relevant ticket, and linked above.  

I'm adding everyone who is involved in some part of this work as assignee's to this ticket.  I'm not sure if that's a good approach going forward for these kinds of coordination tickets, but that's something we can adjust as we go.
