### ISSUE TITLE
Cell Image Library (CIL) Input Stream (epic)

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/damsmanager#316]
## Brief description
[brief description]

- [ ] Products proposal: [_link to proposal ticket?_]
- [ ] Initial scope discussion: [ link to ticket if there is one] _this seems to be something we often do which is helpful, but which makes the initial ticket very long and potentially confusing_

### [function] _I think this might be optional & repeatable depending on the project, for different components of the functionality like the batch edit which has two separate pieces export + overlay_
- [ ] spec written, reviewed , and finalized. #289
- [ ] code written.  #297 #291 
- [ ] testing and updating on QA server.  [link to ticket] _or should this be part of the code item above, perhaps using "review requested" to DOMM (or whomever) prior to a MR?_
- [ ] deployed and tested on production server.  [link to ticket]

_?  anything else ?_

**Comment by arwenhutt** [comment]
@hjsyoo I created a binder ticket for CIL work - I am not sure if the changes to the harvesting process (to use the API instead of their github repo) are included in the comments in #289 or if it would be helpful to have a new ticket for that or not.  Or if there is other work that needs a new ticket or to be linked to this one.  Please edit freely, and we can touch base next week.

**Comment by arwenhutt** [comment]
This ticket is for tracking and coordination across the individual tasks/tickets which are part of this work. I'm adding everyone who is involved in some part of this work as assignee's to this ticket.
